- cmd/internal/cmderr/checks.go
- cmd/internal/ec2/README.md
- cmd/internal/ec2/add.go
- cmd/internal/ec2/ec2.go
- cmd/internal/ec2/postman-insights-agent.service
- cmd/internal/ec2/postman-insights-agent.tmpl
- cmd/internal/ecs/ecs.go
In this PR, we are re-enabling support for EC2 in our agent.
Changes done:
* Replaced `--collection` flag with `--project` in EC2 command
* Added a base`ec2` command since the `setup` command can be confusing.
* So `postman-insights-agent setup ...` -> `postman-insights-agent ec2 setup ...`
* Only `ec2` command also defaults to `ec2 setup`
* Moved the `CheckAPIKeyAndInsightsProjectID` function out from `ecs.go` to `check.go`
* Other small syntactic or typo changes
> [POA-1415] Re-enable support for EC2 commands

- cmd/internal/kube/inject.go
- cmd/internal/kube/injector/injector.go
- cmd/internal/kube/print_fragment.go
- cmd/internal/kube/util.go
also includes [POA-1515] Support "-f -" to read from stdin in injector
As far as I can reconstruct, the preStop problem was that pgrep only checks the process name by default, which is limited to 15 characters.  While we could fix that, I concluded that the only point of the script was to send SIGINT to terminate the agent gracefully, but it now supports receiving SIGTERM directly from Kubernetes, so this is unnecessary.
[POA-1515]: https://postmanlabs.atlassian.net/browse/POA-1515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [POA-1520] Remove preStop script for Kubernetes

- apidump/net.go
- cmd/internal/ecs/add.go
- cmd/internal/kube/util.go
In this PR, we have updated the image URL from the current private ECR URL to the new public ECR URL.
> [POA-1584] Update insights image URL to new public ECR repo

- cmd/internal/ec2/add.go
- cmd/internal/ec2/postman-insights-agent.tmpl
If a user uses the `ec2 start` command with POSTMAN_ENV env var, its value is not set in the env file, which stores other env vars for the systemd service. This will cause an issue for the apidump command since it will then default to prod env.
In this PR, we are preserving the POSTMAN_ENV value in the env file and using that in apidump command which is running as a systemd service.
> [POA-1514] Preserve POSTMAN_ENV in envFile in ec2 start

- apidump/exec.go
- cmd/root.go
- rest/base_client.go
- rest/http.go
* Use safer conversion from `string` to `uint32`.
* Removed support for skipping TLS verification.
> POA-1461 Address code scan

- apidump/apidump.go
- cmd/internal/apidump/apidump.go
- integrations/nginx/backend.go
- trace/backend_collector.go
- trace/backend_collector_test.go
- trace/report_buffer.go
Added `--send-witness-payloads` to `apidump`. When this flag is specified, witness payloads will be preserved and sent to the back end, and only witnesses that are too large (as determined by `--max-witness-size-bytes`) are obfuscated.
> POA-1976 Add option to keep witness payloads

- go.mod
- go.sum
- trace/backend_collector.go
- trace/backend_collector_test.go
- trace/obfuscate.go
* In this PR, we have added support to identify whether a witness payload is obfuscated or not.
* We are setting the `Obfuscation` attribute to `ZERO_VALUE` in the `obfuscation()` function and `NONE` in the else branch in the `queueUpload()` function in `backend_collection.go`.
* `ZERO_VALUE` assignment is still kept to update the value if the witness is obfuscated later in `report_buffer.go` due to the large size
* Also updated the observability-ir version.
> [POA-2003] Set obfuscation enum in witness method meta

- trace/backend_collector.go
- trace/backend_collector_test.go
- trace/util.go
* Add support to obfuscate success (2xx or 3xx) responses always if the sendWitnessPayloads is enabled
* Add a `hasErrorResponses()` util function, which will check the response object of the method and return false if the response code is less than 400.
> [POA-2004] Don't capture payloads of success requests

- trace/backend_collector.go
- trace/backend_collector_test.go
- trace/obfuscate.go
- trace/obfuscation_config.go
- trace/obfuscation_config.yaml
- trace/report_buffer.go
* In this PR, we are adding support for scrubbing sensitive data as an option for `obfuscation` struct
* Added a new `obfuscation_config.go` and `obfusaction_config.yaml` which contains 2 configs:
* `sensitive_keys`: Will be doing an exact match with the header, query_param
* `sensitive_value_regexes`: Will be doing regex match with all the `primitive string` type values
* Authorization and Cookies will be obfuscated always
* We are using relative path for fetching config file
> [POA-2083] Add support for obfuscating sensitive data by default

- cmd/internal/kube/util.go
Adds CPU and memory limits to the injected Kubernetes sidecar.
Tested with a sample deployment file, container looks like:
```
- args:
- apidump
- --project
- svc_0oC1bEWcE2h615Ri01Pp9w
env:
- name: POSTMAN_API_KEY
valueFrom:
secretKeyRef:
key: postman-api-key
name: postman-agent-secrets
- name: POSTMAN_ENV
value: BETA
image: public.ecr.aws/postman/postman-insights-agent:latest
name: postman-insights-agent
resources:
limits:
cpu: 200m
memory: 500Mi
requests:
cpu: 200m
memory: 500Mi
securityContext:
capabilities:
add:
- NET_RAW
```
> [POA-2064] Add resource request and limit to K8S sidecar

- cmd/root.go
- util/printWarningMsg.go
* Add a new `PrintFlagsWarning()` util function to print **BIG** warning message for experimental flags
* Used this function in `root.go` as a preRun task
* For now we have added only 2 flags.
> [POA-1908][POA-1912] Add warning message for experimental flags

- cmd/internal/ec2/add.go
- util/templateUtils.go
* Added a new step in the file creation process to change the permission of files to 600, i.e., the file is only readable and writable to owners
* This is to avoid exposure of sensitive data to other users.
* Added the step in `templateUtils.go` instead of making it EC2-specific.
> [POA-1907] Update permissions of ec2 systemd files

- go.mod
- go.sum
- trace/backend_collector.go
- trace/backend_collector_test.go
- trace/obfuscate.go
- trace/obfuscate_test.go
- trace/report_buffer.go
As part of this, redaction has been reworked to better use visitors.
Tested locally as well. See the `null` field below.
```
$ ./witness_dump --env local org_295oDMFK8b1yS5dwlSTdgP svc_6NiejyYEVpWfziUXJgovV6 lrn_1H3eLS92zSmgyuiwqkGvB5
method: <
id: <
api_type: HTTP_REST
>
responses: <
key: "q2ovkcc4jNQ="
value: <
struct: <
fields: <
key: "api-key"
value: <
primitive: <
string_value: <
value: "*REDACTED*"
>
>
>
>
fields: <
key: "empty"
value: <
list: <
>
>
>
fields: <
key: "null"
value: <
optional: <
none: <
>
>
>
>
fields: <
key: "secret"
value: <
primitive: <
string_value: <
value: "*REDACTED*"
>
>
>
>
>
meta: <
http: <
body: <
content_type: JSON
other_type: "application/json"
>
response_code: 404
>
>
>
>
meta: <
http: <
method: "GET"
path_template: "/"
processing_latency: 4.242 …
```
> POA-2294 Fix redaction for null values

- cmd/internal/apidump/apidump.go
This avoids causing a boot-loop when the POSTMAN_API_KEY environment variable is missing or incomplete, or a command-line parameter is bad.
I don't think we can distinguish initialization from non-initialization errors entirely, but almost all errors that are returned will be config problems.
> [POA-2410] When apidump returns an error, do not exit.

- cmd/internal/apidump/apidump.go
- cmd/internal/apidump/common_flags.go
- cmd/internal/ec2/add.go
- cmd/internal/ec2/ec2.go
- cmd/internal/ec2/postman-insights-agent.service.tmpl
- cmd/internal/ecs/add.go
- cmd/internal/ecs/ecs.go
* In this PR, we have moved out common `apidump` flags from `apidump.go` to `common_flags.go`.
* `common_flags.go` have two functions:
* `AddCommonApiDumpFlags()`: Add the flags to cobra.Command object. It returns the objects to which flag values will be assigned.
* `ConvertCommonApiDumpFlagsToArgs()`: Returns an array of strings (like `--flag value`). It is added to the apidump command in different platform installation configurations.
* The `ecs` and `ec2` commands will read these values and then convert them to flags for `apidump` commands and add them to the definition file (`ecs`) or systems service file (`ec2`)
* The `apidump` command will use these flag values to set the main `apidump` package variables.
> [POA-2129] Separate out common `apidump` flags

- trace/obfuscation_config.yaml
These appear in the /v1/changelog/consumer endpoint in the Version Control service.
> POA-2485: add primarySecret and secondSecret to field list

- cmd/internal/ec2/add.go
- cmd/internal/ec2/ec2.go
With this PR, we are adding a new `--force` flag to `ec2 setup` command which will overwrite existing service files (if any) instead of asking user.
This will be useful in running the command in non-interactive shells, which is used while installing the agent in beanstalk services.
> [POA-2503] Add --force flag in ec2 setup to overwrite files

- cmd/internal/apidump/apidump.go
With this PR, we can now set/override the project ID using an environment variable called `POSTMAN_AGENT_PROJECT_ID`
> [POA-2141] Accept project ID via environment flag

- go.mod
- go.sum
- learn/parse_http.go
- learn/parse_http_test.go
- learn/util_test.go
- Added support for capturing unparsable bodies as raw string
- Also indicates the same using the new Errors field added with the body meta.
> [POA-2516] Parse and persist invalid JSON and YAML bodies

- cmd/internal/ec2/postman-insights-agent.service.tmpl
`ExecStart={{.AgentInstallPath}} apidump --project "${PROJECT_ID}" --interfaces "${INTERFACES}" --filter "${FILTER}" {{.ExtraApidumpArgs}} "${EXTRA_APIDUMP_ARGS}"`
In the above command, if `EXTRA_APIDUMP_ARGS` env var is empty, then apidump will interpret it as quotes (`""`), which will error out with message `[ERROR] accepts 0 arg(s), received 1`.
Remove the quotes surrounding the environment command.
> [POA-2570] Remove quotes around EXTRA_APIDUMP_ARGS

- apidump/apidump.go
- cmd/internal/apidump/apidump.go
- cmd/internal/apidump/common_flags.go
* Added a new flag, `--repro-mode`, which is the equivalent to `--send-witness-payload` flag.
* The `--send-witness-payload` flag will be removed in the future.
* Renamed variables wherever possible. However, the variable name was not changed in `backend_collection.go` because `sendWitnessPayloads` is more appropriate there, as it better reflects its functionality.
> [POA-2701] Add --repro-mode flag

- apidump/apidump.go
A follow-up PR from https://github.com/postmanlabs/postman-insights-agent/pull/65#discussion_r1938541053
NOTE: Do not merge before https://github.com/postman-eng/observability-superstar-service/pull/2256 is released all the way through to PRODUCTION
> [POA-2766] Send accurate duration in initial and success telemetry

- cmd/internal/kube/daemonset/daemonset.go
In this PR, we have added a worker which will keep on check the status for pods for which we are running pidump process
* Start a ticker which will keep on checking the health regularly
* If pod's status moves to a final state, i.e., Suceeded or Failed then call the apidump stop process
> [POA-2781] Implement pods health checker

- apidump/apidump.go
- cfg/credentials.go
- cmd/internal/cmderr/checks.go
- cmd/internal/kube/daemonset/daemonset.go
- cmd/internal/kube/inject.go
- cmd/internal/legacy/specs.go
- integrations/nginx/backend.go
- rest/auth_handlers.go
- rest/base_client.go
- rest/front_client.go
- rest/http.go
- rest/learn_client.go
- setversion/run.go
- telemetry/telemetry.go
- util/util.go
In this PR, we have done changes in the auth handling method of rest client and also handle API Keys for separate pods apidump process
* We will be storing the API keys in the viper config and use pod name as profile
* Refactored the rest client to receive the auth handler as the interface parameter
* Created 2 separate auth handlers. 1) for default flow 2) For new pod process flow
* In stopapidump process unset the required configs.
> [POA-2780] Refactor rest client to handle multiple auth ways

- data_masks/redactor.go
Before:
```
[INFO] Running learn mode on interfaces lo, wlan0
[INFO] Send SIGINT (Ctrl-C) to stop...
^C[INFO] Received interrupt, stopping trace collection...
panic: close of closed channel
```
After:
```
[INFO] Running learn mode on interfaces lo, wlan0
[INFO] Send SIGINT (Ctrl-C) to stop...
^C[INFO] Received interrupt, stopping trace collection...
[INFO] Trace collection stopped
[INFO] Did not capture any TCP packets matching the filter. This may mean your filter is incorrect, such as the wrong TCP port.
[ERROR] No HTTP calls captured! 🛑
[ERROR] Error during initiaization: API trace is empty
[INFO] This process will not exit, to avoid boot loops. Please correct the command line flags or environment and retry.
```
> POA-2904 Fix double close in redactor

- data_masks/redactor.go
Tested locally:
```
[INFO] Running learn mode on interfaces lo, wlan0
[INFO] Send SIGINT (Ctrl-C) to stop...
^C[INFO] Received interrupt, stopping trace collection...
[INFO] Trace collection stopped
[INFO] Did not capture any TCP packets matching the filter. This may mean your filter is incorrect, such as the wrong TCP port.
[ERROR] No HTTP calls captured! 🛑
[ERROR] Error during initiaization: API trace is empty
[INFO] This process will not exit, to avoid boot loops. Please correct the command line flags or environment and retry.
```
> POA-2904 Use sync.Once

- cmd/internal/kube/daemonset/pods_healthcheck_worker.go
- cmd/internal/kube/daemonset/telemetry.go
I observed some corner cases in the beta environment, where some services are directly moving to the final state before going to the running state.
This could happen if there are some config issues like `CreateContainerConfigError`.
For example, here we got a Pod Delete event where the pod's status is still Pending.
```
[31m[ERROR] [0mPod status is in unknown state, pod name: cronjob-scheduled-work-29008098-8mgxh, status: Pending
[31m[ERROR] [0mFailed to change pod state, pod name: cronjob-scheduled-work-29008098-8mgxh, from: PodPending to: PodTerminated, error: Invalid current state for pod cronjob-scheduled-work-29008098-8mgxh: PodPending
```
For such corner cases, I have added an if condition, i.e., if a pod doesn't exist anymore, then move its state to `PodTerminated` irrespective …
> [POA-2928] Cover corner case of pod not coming up at all

- cmd/internal/kube/daemonset/daemonset.go
- cmd/internal/kube/daemonset/kube_events_worker.go
- integrations/kube_apis/kube_apis.go
- integrations/tests/kube_cri_apis/main.go
This pull request fixes the bug where we consider the first container to be the main container and only check it for env vars. In some cases, like service mes, the main container won't be the first container.
So we will now check for environment variables in all containers and use the container that has all the required environment variables.
Changes:
* Removed the unused `allRequiredEnvVarsAbsentErr` error and its corresponding handling in `StartProcessInExistingPods` and `handlePodModifyEvent` methods
* Simplified the error message for `requiredEnvVarMissingErr` to "required environment variables missing" since it is not printed anywhere.
* Updated the `inspectPodForEnvVars` method to retrieve UUIDs for all containers in a pod instead of just the main container
* Replaced the …
> [POA-3041] Check all containers for env vars

- cmd/internal/ec2/add.go
This pull request includes changes to the `cmd/internal/ec2/add.go` file to enhance the handling of the `postman-insights-agent` service.
Enhancements to service handling:
* [`cmd/internal/ec2/add.go`](diffhunk://#diff-de4c0d4aa9b0bc2881e1a3420db0ab595602fc4d945fbad5383e1586cd62a8d5R36-R38): Added a new constant `active` to represent the active state of the `postman-insights-agent` service.
* [`cmd/internal/ec2/add.go`](diffhunk://#diff-de4c0d4aa9b0bc2881e1a3420db0ab595602fc4d945fbad5383e1586cd62a8d5R275-R294): Modified the `enablePostmanInsightsAgent` function to check if the `postman-insights-agent` service is active, and if so, restart it with the new configurations. This includes handling errors and providing informative messages to the user.
> [POA-2849] Add systemd restart for already running service in ec2

- cmd/root.go
- util/printWarningMsg.go
This change will display the following warning when the `--repro-mode` flag is set on a command that supports it:
```
[WARNING] Turning on the --repro-mode flag enbales the Postman Insights Agent to send payload data to the Postman cloud.
The Postman Insights Agent will automatically redact values in a default list of sensitive fields, as well as any additionally specified fields.
For more information, please see: https://postmanlabs.atlassian.net/wiki/spaces/PIIUG/pages/5513740658/Data+handling+and+access#When-Repro-Mode-is-enabled.
```
---
With `--log-format` set to `color`:
With `--log-format` set to `plain`:
With `--log-format` set to `json`:
---
I manually verified, doesn't look like we have a test suite for this, that the warning is only shown on on commands that actually support …
> [POA-2246] Display warning when repro mode flag is used

- cmd/internal/kube/daemonset/apidump_process.go
- cmd/internal/kube/daemonset/daemonset.go
- cmd/internal/kube/daemonset/kube_events_worker.go
- cmd/internal/kube/daemonset/pod_args.go
- cmd/internal/kube/daemonset/pods_healthcheck_worker.go
This pull request includes changes to prevent the agent from going into a panic state while closing the apidump process during the daemonset process shutdown and other changes.
**Problem:**
* Before changing the state of the apidump process to the final state and then calling the `StopApiDumpProcess`, we are checking if the process is already in the final state to avoid `StopApiDumpProcess` being called multiple times.
* But this final state check is not sync, due to which dirty read issue can happen and `StopApiDumpProcess` can be called multiple times which will send signal to already stopped channel hence causing program to go to panic state.
**Changes:**
Improvements to state handling:
* Added a check in `changePodTrafficMonitorState` to prevent state changes if the pod is already in …
> [POA-3109] Handle panic while stopping apidump process while daemonset exit

- cmd/internal/ec2/postman-insights-agent.service.tmpl
Adds CPU and Memory limits to the postman insights service file.
Summary:
- Agent process CPU time will be prioritized lower than other services.
- Agent process will be restricted to 85% of a single CPU core.
- Agent process will be throttled by the OS if it exceeds 750MB of memory.
- Agent process will be OOM Killed if it exceeds 1GB of memory.
- Agent process will be restarted on failure.
> [POA-2944] Add agent cpu and memory limits when running on ec2

- cmd/internal/ec2/postman-insights-agent.service.tmpl
Manually testing the cgroup cpu and memory limits in an EC2 instance revealed a problem with the values we set in the `.service` config file. As it turns out, we can't place comments on the same line as the value because the comments will be interpreted as part of the value.
Running `journalctl -fu postman-insights-agent.service` in the ec2 instance revealed the following logs:
```
Mar 21 00:51:45 ip-172-31-76-65.ec2.internal systemd[1]: /usr/lib/systemd/system/postman-insights-agent.service:14: Invalid CPU weight, ignoring: 90 #comment
Mar 21 00:51:45 ip-172-31-76-65.ec2.internal systemd[1]: /usr/lib/systemd/system/postman-insights-agent.service:15: Invalid CPU quota '50% #comment', ignoring.
Mar 21 00:51:45 ip-172-31-76-65.ec2.internal systemd[1]: …
```
> Fix ec2 daemon service cpu & memory values

- apidump/apidump.go
- cmd/internal/apidump/apidump.go
Ensure that the agent process exits if the process receives a `SIGINT` or `SIGTERM` signal.
**Tests:**
- Validate process will exit if TTY is set:
- Created a new Ubuntu arm64 VM
- Built agent with `make docker-build`
- Ran agent in VM and sent a `Ctrl-C` signal
- Confirmed agent process exited
- Validate process will exit when run as daemon:
- Created a new Ubuntu arm64 VM
- Built agent with `make docker-build`
- Added a new `.service` file
- Reloaded systemd configuration with `systemctl daemon-reload`
- Enabled service with `systemctl enable postman-insights-agent.service`
- Confirmed successful daemon startup with `journalctl -fu postman-insights-agent.service`
- Sent SIGINT signal with `kill -2 {process-id}`
- Confirmed agent process exited
**Logs:**
*Interactive (TTY is set) logs:* …
> Ensure agent exits if process receives SIGINT or SIGTERM signal

- apidump/apidump.go
- cmd/internal/apidump/apidump.go
- cmd/internal/kube/daemonset/kube_events_worker.go
Changes:
* `apidump/apidump.go`: Refactored the logic to check for dropping Nginx traffic by directly using the `a.DropNginxTraffic` flag.
* `cmd/internal/apidump/apidump.go`: Added the `DropNginxTraffic` flag to the `apidumpRunInternal` function, allowing it to be set via the `viper` configuration.
> [POA-3263] Set drop-nginx-traffic arg at apidump cmd also

- apidump/summary.go
- pcap/stream.go
- trace/backend_collector.go
- trace/backend_collector_test.go
Added witness latency calculation tests. Specifically the following scenarios are now being tested:
- the request and the response have 8 ms of latency
- the request and the response have 0 ms of latency
- the request and the response overlap by -1 ms of latency
- the request and the response fully overlap each other have 0 ms of latency
- the request and the response are in the wrong order have -4 ms of latency
- the request and the response timestamps are the zero value have 0 ms of latency
- a stream with two interleaved request and response each with 3 ms of latency
- two pipelined requests and responses have 0 ms of latency
Added 2 validations in the stream processing layer:
- if the first or last packet timestamps are the default zero value, override to `time.Now()`.
- if the last …
> Add latency calculation tests & logs

- pcap/net_parse.go
- pcap/stream.go
I'm suspicious of the `toPNT` call within `reassemblyComplete`. I wonder if these is where we are getting the zero timestamp.
> Emit log if we have network traffic on reassembly complete

- pcap/stream.go
Latest experiment indicates that pcap is not the issue, packets are getting non-zero timestamps. The question then becomes: How is it possible to observed parsed network traffic where both the first packet and last packet timestamps are zero if we can definitely see that pcap timestamped each packet correctly?
I think this indicates that the zero timestamp issue must be coming from within the the assembler or within the `stream.go` file. The following change will confirm which of the two.
Either:
- The assembler does indeed manipulate the timestamps, somehow setting them to zero.
- The parsed network traffic we observe with zero timestamps is actually `DroppedBytes`.
> Log the type of parsed network traffic

- usage/usage.go
When calculating the `relativeCPU` we divide `selfCPU` by `allCPU` if both values are zero we end up with `NaN`. Any mathematical operation with a `NaN` value results in a `NaN` value. So we must correct this to ensure later on we can serialize the value.
> Check for NaN value in usage

- apidump/apidump.go
- go.mod
- go.sum
- trace/rate_limit.go
- trace/rate_limit_test.go
Count the number of rate limited requests. Report the configured rate limit during the initial telemetry report and with each stats capture report.
> [POA-3519] Report rate limited requests & configured rate limit

- go.mod
- go.sum
- trace/stats.go
With this change each telemetry report will include the count of http requests, responses, rate limited requests, etc. during the observation window. These count get reset each time we report.
> Report observation window counters

- apidump/apidump.go
- go.mod
- go.sum
These changes will report the observation window start and duration. The observation window resets every time we send a telemetry report. These new values will help us calculate averages more precisely without flattening them over a long observation session. Additionally the window start time will help us build better rollup windows.
TODO:
> [POA-3519] Report telemetry observation window start and duration

- cmd/root.go
- cmd/supervisor.go
With this patch, we use the agent process to be it's own supervisor. This is controlled with __X_AKITA_NO_FORK environment variable. If it's set to "1", the process won't fork itself and we will have the old behaviour. For all other values, the first thing it is going to do is fork and execute itself. The root process will then monitor the child process and restart it if necessary.
> Add a supervisor process to the agent

- cmd/internal/kube/inject.go
- cmd/internal/kube/print_fragment.go
- cmd/internal/kube/util.go
Adds the common apidump flags to the `kube inject`, `kube helm-fragment`, and `kube tf-fragment` commands.
> [POA-3567] add common apidump flags to kube commands

- cmd/internal/kube/daemonset/daemonset.go
- cmd/internal/kube/daemonset/kube_events_worker.go
- cmd/internal/kube/run.go
I started by adding all of the common apidump flags to the `kube run` command, but then decided against it. I'm not sure if it makes sense to set `Interfaces`, `HostAllowlist`, etc. at the daemonset level. So for now I am just adding the `rate-limit` flag.
> [POA-3567] Add rate-limit flag to kube run command

- cmd/internal/ec2/add.go
New output:
```
❯ sudo POSTMAN_ENV=beta POSTMAN_API_KEY=PMAK-**** ./bin/postman-insights-agent ec2 setup --project svc_11PHSa7GenVKdVCZN9r4Ya --repro-mode
Password:
[INFO] Telemetry unavailable; no Amplitude key configured.
[INFO] This is caused by building from source rather than using an official build.
[INFO] Postman Insights Agent 0.0.0
[WARNING] Turning on the --repro-mode flag enables the Postman Insights Agent to send payload data to the Postman cloud.
The Postman Insights Agent will automatically redact values in a default list of sensitive fields, as well as any additionally specified fields.
It is your reponsibility to ensure that any additional sensitive fields are appropriately redacted.
For more information, please see: https://learning.postman.com/docs/insights/repro.
By …
```
> [POA-3798] Show error message when using ec2 setup on macos

- .gitignore
- Makefile
- cmd/internal/kube/print_fragment.go
- data_masks/redaction_test.go
- rest/interface.go
- trace/backend_collector_test.go
In this PR, we have moved the `interface.go` mock file outside of its own package to the main `rest` package.
**Why?**
Since we don't push mock files to VCS _(which is the right practice)_ the `mock` package is missing from the publicly available package. This was causing issues with the `go mod tidy` command in the superstar service, where the package is used.
```
go: finding module for package github.com/postmanlabs/postman-insights-agent/rest/mock
go: akitasoftware.com/superstar/cli-postman imports
github.com/postmanlabs/postman-insights-agent/cmd imports
github.com/postmanlabs/postman-insights-agent/pcap imports
github.com/postmanlabs/postman-insights-agent/trace tested by
github.com/postmanlabs/postman-insights-agent/trace.test imports …
```
> [POA-3499] Remove separate package for interface mock

- cmd/internal/kube/daemonset/apidump_process.go
Different pods from the same daemon were reporting telemetry with the same client ID.  If two pods from the same project were on the same node, this caused duplicate client IDs to be reported within that project.
> [POA-3899] Allocate a new ClientID for each apidump process

- apidump/apidump.go
- apispec/defaults.go
- cmd/internal/apidump/apidump.go
- cmd/internal/kube/daemonset/apidump_process.go
- integrations/nginx/backend.go
- trace/backend_collector.go
- trace/backend_collector_test.go
- trace/report_buffer.go
Changes:
- Reduces the frequency we check the witness pair cache for partial witnesses from 30 seconds to 5 seconds. 
- **Note:** the partial witness must still go unpaired for at least a minute before being flushed
- Reduce the witness upload batch size from 60MB to 30 MB. 
- **Note:** max witness size is 30MB, so we can't go any lower here.
- Refactors the witness upload logic to be asynchronous**
- ** **Note:** under very high load it might still be possible to have two concurrent witness uploads at the same time as a `Flush` call. If that were to happen the `Flush` call would block until one of the concurrent uploads puts a `UploadReportsRequest` instance back in the channel.
> [POA-4077] Reduce buffering & flush asynchronously

- integrations/kube_apis/kube_apis.go
Makes requests to the Kubernetes control plane retryable. 
@mgritter the retry policy I put together will do exponential backoff over 24 hours. With retries roughly spaced out as so:
```
10.287155ms
20.192638ms
40.386001ms
83.404268ms
175.904924ms
333.353542ms
688.884691ms
1.403393012s
2.67855389s
5.186614127s
10.281018786s
21.183672466s
43.16988402s
1m24.308865015s
2m45.132908715s
5m40.246872485s
11m44.495217975s
23m51.207256068s
44m2.192306181s
1h28m45.802551329s
3h10m48.696636639s
6h11m47.786646951s
12h29m6.553887233s
23h53m43.937483075s
```
Let me know if you think this is too much or too little. Or if you'd like me to tweak the spacing between retries.
Also, let me know if you would like me to also add a loop around `StartDaemonset` in `cmd/internal/kube/run.go` that checks for …
> [POA-4122] Make kubernetes requests retryable

- pcap/net_parse.go
- pcap/pcap.go
- pcap/run.go
- trace/backend_collector.go
Adds metrics to the agent letting us know:
- How long is the buffer of pcap capture packets
- How long is the buffer of unprocessed packets
- How long is the buffer of parsed network traffic
- How long is the buffer of unpaired partial witnesses
> [POA-4078] Add agent metrics

- apidump/apidump.go
- integrations/nginx/backend.go
- pcap/net_parse.go
- pcap/net_parse_test.go
- pcap/pcap.go
- pcap/pcap_replay_test.go
- pcap/run.go
- trace/backend_collector.go
- trace/backend_collector_test.go
As far as I can tell the traceTags should be flowing through the codebase, so not sure why we are not seeing them on the backend. This PR attempts to log the pod name by passing the tracetags to the apidump layer.
> [POA-4157] Capture service ID on buffer metrics logs

- cmd/internal/kube/daemonset/apidump_process.go
- cmd/internal/kube/daemonset/daemonset.go
- cmd/internal/kube/daemonset/kube_events_worker.go
- cmd/internal/kube/daemonset/pod_args.go
- cmd/internal/kube/daemonset/pod_args_test.go
- cmd/internal/kube/daemonset/pods_healthcheck_worker.go
This pull request includes changes to prevent the agent from going into a panic state while closing the apidump process during the daemonset process shutdown and other changes.
**Problem:**
* Before changing the state of the apidump process to the final state and then calling `StopApiDumpProcess`, we check if the process is already in the final state to avoid calling `StopApiDumpProcess` multiple times.
* But this final state check is not synced, which can cause a dirty read issue. `StopApiDumpProcess` can also be called multiple times, which will send a signal to an already stopped channel, causing the program to go into a panic state.
**Changes:**
Improvements to state handling:
* Added a check in `changePodTrafficMonitorState` to prevent state changes if the pod is already in a final …
> [POA-3109] Handle panic while shutting down daemonset

- apidump/apidump.go
- apidump/net.go
- cmd/internal/cmderr/checks.go
- cmd/internal/kube/daemonset/daemonset.go
- cmd/internal/kube/inject.go
- cmd/internal/legacy/specs.go
- integrations/nginx/backend.go
- integrations/nginx/install.go
- pcap/net_parse.go
- pcap/net_parse_test.go
- pcap/pcap_replay_test.go
- pcap/run.go
- rest/base_client.go
- rest/front_client.go
- rest/learn_client.go
- setversion/run.go
- telemetry/telemetry.go
- trace/backend_collector.go
- trace/backend_collector_test.go
- util/util.go
In this PR, we have changed the telemetry package to provide telemetry support for subprocesses (go routines) under the main processes.
Changes:
- Telemetry package changes:
- Move the global functions under an interface and struct model.
- Created a root (Default) telemetry object, which is used by the existing processes for sending telemetry
- A new constructor which will create a new scoped telemetry object.
- Removed the irrelevant analytics functions which were used in deprecated functions.
- apidump and rest client changes:
- Change the way the error report function is set in the base client, not it will be passed as a parameter to the constructor, just like the auth handler
- Set a global package telemetry variable in the apidump package to use it in various functions instead of …
> [POA-3089] Change telemetry package to handle daemon set sub processes

- apidump/apidump.go
- cmd/internal/apidump/apidump.go
- cmd/internal/apidump/common_flags.go
- integrations/nginx/backend.go
- trace/backend_collector.go
- trace/backend_collector_test.go
- trace/util.go
We have added a new flag to get the list of paths for which we will always send the payloads, regardless of the response code.
Changes:
1. Added a new flag `always-capture-payloads` flag, marked as hidden.
2. Pass this flag's value to the backend collector
3. Construct a regex slice from the list, if any regex fails to compile, log it and continue
4. Move the witness checks to util.go file and combine under a common function `shouldCapturePayload()`
4. Added test case.
> [POA-4390] New flag to always capture payloads
